project:
  type: website
  output-dir: _site

website:
  title: "Research Approaches II: Data Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: docs/r_tutorial.md
        text: R Introduction
      - href: docs/anova.qmd
        text: ANOVA  
      - href: docs/t_test.qmd
        text: T-test
      - href: docs/methylome_analysis.md
        text: Methylome Analysis

    right:
      - icon: github
        href: https://github.com/karlssonlaboratory/mi8016-Research-Approaches
      - icon: house-door
        href: https://karlssonlab.se/
        text: Karlssonlab

format:
  html:
    code-annotations: below
    theme: 
      light: pulse
      dark: darkly
    highlight-style:
      light: arrow
      dark: breezedark

execute:
  warning: false
  message: false